### ISSUE TITLE
Ensure that long-term use of farolero won't cause memory issues with Keywords

### ISSUE THREAD

**Issue by IGJoshua** [IGJoshua/farolero#13]
Currently farolero uses keywords as jump targets because it makes it easy and fast to check, but this could be a problem for long-running processes because it uses randomly-generated keywords as jump targets, and keywords are interned, which means that they will not be garbage collected.

This can be mitigated by changing the type returned by `make-jump-target` to something that is more memory friendly but still fast for comparison (and ideally faster for construction).

Some ideas for ways to do this are:
* Keeping a 64-bit atomic integer global and using fetch_add(1) (with overflow) to get targets
* Just using symbols with `gensym`, without coercing them to keywords (though this may make equality testing more expensive if I can't find a way to use `identical?`)

**Comment by phoe** [comment]
I'm not a Clojurian, but I learn as I go.

Gensyms as `go` tags in the CL version work fine, since they are `eq`-comparable and easily garbage-collectable. It seems that Clojure's `identical?` works on symbols in the same way as `eq` in CL, since `(let [x (gensym)] (identical? x x)) ;=> true`. It also seems that symbols can be garbage collected in Clojure.

**Comment by IGJoshua** [comment]
Symbols can be garbage collected in Clojure, it's true, but Keywords cannot as far as I am aware. Moreover the issue isn't gensymming stuff at compile time, but rather the fact that I have to do it at runtime to keep track of which blocks are currently on the stack and to allow block and tagbody to be reentrant.

Also I do want to note that while yes, in the case of gensyms, `identical?` on symbols acts like `eq` on symbols, this isn't true for symbols in general because Clojure doesn't intern symbols. You can have equal symbols that are not identical.

In any case, I've fixed the issue by replacing the implementation with an auto-incrementing atomic integer, and all tests pass on both Clojure and ClojureScript, so I'm satisfied with this.

**Comment by phoe** [comment]
> but rather the fact that I have to do it at runtime to keep track of which blocks are currently on the stack and to allow block and tagbody to be reentrant.

Random idea - maybe https://github.com/phoe/cafe-latte will be of use here?

And, yes, an atomic 64-bit integer should be unique enough for all practical purposes.
