### ISSUE TITLE
Compile error: Unable to resolve symbol: ex-message in this context, compiling:(farolero/core.cljc:932:12)

### ISSUE THREAD

**Issue by enspritz** [IGJoshua/farolero#14]
Hi!

While going through the motions to replace `special` with `farolero` in Ash Ra Template 0.6.0 on a [dedicated branch](https://github.com/vivid-inc/ash-ra-template/tree/farolero), I am encountering some blockers. Hopefully with regard to ART's source code, we are talking simple, by-the-book usage of farolero.

With farolero version 1.4.1, tests fail due to spec conformance errors. And with 1.4.0 and several versions prior, there is a non-debilitating error message in conjunction with Clojure 1.9.0, meaning code does compile and tests pass 100%, but the compile error message causes lein to fail leading to premature abort in `bin/test.sh`, plus consternation in us onlookers.

**Comment by enspritz** [comment]
With Farolero 1.4.1, the same Exception message with Clojure 1.9.0 is produced.

**Comment by phoe** [comment]
Not a Clojure programmer, but lemme try.

> Exception in thread "main" java.lang.RuntimeException: **Unable to resolve symbol: ex-message in this context**, compiling:(farolero/core.cljc:932:12)

Might be here:

https://github.com/IGJoshua/farolero/blob/9bb82a1c9b10cdc82629d672431f11ebf6c17b1d/src/cljc/farolero/core.cljc#L938-L946

No idea what's going on here - `ex-message` seems to be a well-defined in function Clojure, see https://clojuredocs.org/clojure.core/ex-message.

Regarding the test failure - maybe this is a fallout from the recent change (36f0d5b5d813) that stopped using keywords and started using integers. We can see that here:

https://github.com/IGJoshua/farolero/blob/9bb82a1c9b10cdc82629d672431f11ebf6c17b1d/src/cljc/farolero/core.cljc#L77-L81

But then:

https://github.com/IGJoshua/farolero/blob/9bb82a1c9b10cdc82629d672431f11ebf6c17b1d/src/cljc/farolero/core.cljc#L84-L101

In L94, the block name becomes the result of `make-jump-target`, which is not a keyword anymore. But the spec for `block*`, L66, seems to say that the argument to `block*` should be a keyword:

https://github.com/IGJoshua/farolero/blob/9bb82a1c9b10cdc82629d672431f11ebf6c17b1d/src/cljc/farolero/core.cljc#L65-L68

Which looks like a type error.

**Comment by IGJoshua** [comment]
@phoe you're right on that, I made an implementation change in 1.4.1 that I made the mistake to not check the spec for that function. The public api is intended to exclusively be keywords, I'll look to getting a new release to fix this issue.

The first problem with `ex-message` is due to that var being introduced in 1.10.0, so this is expected. What isn't expected is I didn't think farolero would see much usage with older Clojure versions. Nothing in particular should prevent it however except perhaps cljc support.

@enspritz what is the earliest version of Clojure you are looking to support?

**Comment by enspritz** [comment]
Thanks @phoe and @IGJoshua for the quick replies.

@IGJoshua Clojure 1.9.0, but there is no adoption yet, so I foresee zero problems in advancing the earliest supported version to Clojure 1.10.0. In fact, I'll do that right now.

**Comment by IGJoshua** [comment]
Alright, good to know. I still want to update the spec and push a new release. Thanks for filing the report!

**Comment by enspritz** [comment]
Sounds good -- waiting with baited breath!

**Comment by IGJoshua** [comment]
Version 1.4.2 is out on clojars and should fix this issue!
