### ISSUE TITLE
Babashka support

### ISSUE THREAD

**Issue by NoahTheDuke** [IGJoshua/farolero#18]
I'm thinking about using Farolero in [Splint](https://github.com/NoahTheDuke/splint) but that requires farolero to support [babashka](https://github.com/babashka/babashka).

Would you have any interest in supporting babashka?

**Comment by IGJoshua** [comment]
Hey! I definitely am interested in getting support for babashka going, it honestly seems like a really good place for farolero to show its usefulness.

The current restriction on babashka support to my understanding is that I rely on a java class I compiled, which isn't going to be available inside babashka, but I *can* replicate the behavior by throwing some different exception type, although it will be more brittle.

Do you want to assist with porting to babashka and have me provide support for you in that endeavor? If not, would you have resources which could be used in helping me to port it?

**Comment by NoahTheDuke** [comment]
Yeah, that's one big issue, and the other might be relying on macrovich tho I'll have to play around with it.

I'm willing to take this on myself as I'll be the one using it primarily, but I'll definitely reach out when I have questions. I opened this to make sure that I don't put in a bunch of work just to throw it all away if you didn't care to support it hah.
