### ISSUE TITLE
Failing tests for interactive debugger

### ISSUE THREAD

**Issue by NoahTheDuke** [IGJoshua/farolero#4]
Hey there! The two tests for the interactive debugger don't work because `*debugging-hook*` is set to the `throwing-debugger` by default. Looks like commit 113507979eb2d5f187dc9a544a2083d1bbc8cb75 is the one that changed this. Should the tests be changed to reflect this?

https://github.com/IGJoshua/farolero/blob/d82c3b6e79afb8a95db40258de6d4e2cc2128be9/test/clj/farolero/core_test.clj#L73-L79

https://github.com/IGJoshua/farolero/blob/d82c3b6e79afb8a95db40258de6d4e2cc2128be9/test/clj/farolero/core_test.clj#L187-L193

**Comment by IGJoshua** [comment]
Ah, good catch! These tests should be changed to use `with-redefs` to test the system debugger. I'll update this tonight, although if they pass after that fix there'll be no need to make a new release.

**Comment by IGJoshua** [comment]
Fixed on develop!
