### ISSUE TITLE
Unused gensyms

### ISSUE THREAD

**Issue by NoahTheDuke** [IGJoshua/farolero#5]
In a couple of places, a gensym is created in a let block and then is unused, while an automatic gensym matching the name of the function is used immediately following. The first occurrence is in `tagbody`:

https://github.com/IGJoshua/farolero/blob/d82c3b6e79afb8a95db40258de6d4e2cc2128be9/src/cljc/farolero/core.cljc#L126-L127

Is this on purpose?

**Comment by IGJoshua** [comment]
Thanks for pointing that out! There used to be catch blocks in all those places that needed a name for the exception, but now I just use the `block` macro. These aren't hurting anything, so I won't make a new release for this, but I'll get them removed in the latest develop!

**Comment by IGJoshua** [comment]
Fixed on develop!
