### ISSUE TITLE
handler-case and :no-error

### ISSUE THREAD

**Issue by NoahTheDuke** [IGJoshua/farolero#8]
In the CLHS section for `HANDLER-CASE`, it [says](http://clhs.lisp.se/Body/m_hand_1.htm): "If execution of expression returns normally and a no-error-clause does exist, [...]" The current farolero implementation does not match this, as the `src` block doesn't denote whether it's returning from the primary path or an error, so it unconditionally calls `multiple-values-call` on the return value.

**Comment by IGJoshua** [comment]
Closed by #9
